version: '3.8'
services:
  dynamic-api:
    container_name: dynamic-api-app  # This forces a simple name
    build: .
    restart: always
    networks:
      - tunnel_net

  tunnel:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    # We add --no-autoupdate for stability on Raspberry Pi
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - tunnel_net
    depends_on:
      - api

networks:
  tunnel_net:
    driver: bridge