version: '3.8'
services:
  api:
    build: .
    restart: always
    # We don't even need 'ports:' here anymore! 
    # The tunnel talks to the API over the internal Docker network.
    expose:
      - "9010"

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN} # Get this from Cloudflare Zero Trust Dashboard

      